/* helpids.h - generated by ACUCOBOL-GT v3.2 Alpha 1 */
/* Generated Wed Mar 26 09:20:41 1997 */

#define NO_HELP                       	1
#define FIELD_1_HELP                  	2
#define FIELD_2_HELP                  	3
#define EXIT_HELP                     	4
#define TEXT_HELP                     	5

/* End of helpids.h */
