       01  CA-MESSAGE-LINK external .
           05 CA-MESSAGE-TYPE           PIC 9.
           05 CA-MESSAGE-RESP           PIC 9(02).
           05 CA-MESSAGE-1              PIC X(70).
           05 CA-MESSAGE-2              PIC X(70).
           05 CA-MESSAGE-3              PIC X(70).
           05 CA-MESSAGE-ID             PIC xxx.
           05 CA-ERR-FILE               PIC X(30).
           05 CA-CALL-FAIL-CODE         PIC XXX.
           05 CA-STU .
              10 CA-STAT                PIC XX.
                 88 CA-STAT-OK  VALUE x"0000" THRU "0900".
              10 CA-EXTEND-STATUS       PIC XXXX.
           05 CA-ERR-BUF                PIC X(80).
           05 CA-HINT-LINE              PIC X(80).
           05 CA-LINE-HINT-MESSAGE      PIC 99.
