//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service2Soap", Namespace="http://tempuri.org/")]
public class Service2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public Service2() {
        this.Url = "http://jlynch-2p/WebService2/WebService2.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMsg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void SendMsg(string msg) {
        this.Invoke("SendMsg", new object[] {
                    msg});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendMsg(string msg, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendMsg", new object[] {
                    msg}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndSendMsg(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_TotalNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int get_TotalNumber() {
        object[] results = this.Invoke("get_TotalNumber", new object[0]);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginget_TotalNumber(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("get_TotalNumber", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public int Endget_TotalNumber(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_LastMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string get_LastMessage() {
        object[] results = this.Invoke("get_LastMessage", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginget_LastMessage(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("get_LastMessage", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string Endget_LastMessage(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
}
